global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'snail-member-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['snail-member:8080']