{
 "title": "Auth Fail Type Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "BLACK_LIST",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_fail_count_total{type=\"BLACK_LIST\"}"
    }
   ]
  },
  {
   "title": "BAD_CREDENTIALS",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_fail_count_total{type=\"BAD_CREDENTIALS\"}"
    }
   ]
  },
  {
   "title": "TOKEN_EXPIRED",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_fail_count_total{type=\"TOKEN_EXPIRED\"}"
    }
   ]
  },
  {
   "title": "AUTH_SERVER_ERROR",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_fail_count_total{type=\"AUTH_SERVER_ERROR\"}"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_fail_count_total{type=\"UNKNOWN\"}"
    }
   ]
  }
 ]
}